### ISSUE TITLE
Simple Neo4j::Driver type

### ISSUE THREAD

**Issue by petr-fischer** [jgaskins/neo4j.cr#8]
Hello! Can you add at least an alias (if not common superclass) like this:

```crystal
module Neo4j
  alias Driver = Cluster | DirectDriver
end
```

So if we are storing Neo4j connection somewhere in our own getter, we don't need to use the union `Cluster | DirectDriver`.

Thanks!

**Comment by jgaskins** [comment]
I've run into that irritation myself in a few apps, too. It's not great.


I have a branch that, among other things, makes Driver a superclass of

both <https://github.com/jgaskins/neo4j.cr/compare/experimental-bolt-
conversion#diff-b49b98fc611ceadb9ae98f54a0e4d958R6>.

I probably would've merged it sooner if I realized anyone but me was
actually using this shard. 😂

On September 22, 2020, GitHub <notifications@github.com> wrote:
> Hello! Can you add at least an alias (if not common superclass) like

> this:
>
> module Neo4j alias Driver = Cluster | DirectDriver end
> So if we are storing Neo4j connection somewhere in our own getter, we

> don't need to use the union Cluster | DirectDriver.
>
> Thanks!
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jgaskins/neo4j.cr/issues/8>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA2NLKD65RNLEOIEUQ4FDLSHDBZJANCNFSM4RV6HX6A>.

**Comment by jgaskins** [comment]
TIL the email replies don't look amazing. That branch is [here](https://github.com/jgaskins/neo4j.cr/compare/experimental-bolt-conversion#diff-b49b98fc611ceadb9ae98f54a0e4d958R6).

Anyway, I'll try to get that branch merged this week and get a new release out. It started as a simple experiment and kinda got out of hand as I kept adding to it.

**Comment by petr-fischer** [comment]
> I probably would've merged it sooner if I realized anyone but me was actually using this shard.

Yeah - we are using your shard and we love all the features like domain mappings, query casting etc!
Don't rush, keep it stable. :)
Thanks for your work!

**Comment by jgaskins** [comment]
@petr-fischer It occurred to me that I won't be able to merge that branch yet in a way that will be compatible with your Neo4j DB. One of the changes in that branch is an [upgrade to Bolt v4](https://github.com/jgaskins/neo4j.cr/commit/0be10c76f45329d12c17e3e917adf90c4466fe61), which requires Neo4j 4.0-4.1. If you're using the current release, you're probably on Neo4j 3.4-3.5. Last time I spoke with the driver team at Neo4j, they said that the Neo4j server only supports the current and most recent Bolt version, and because I don't have a whole team working on this driver I've only been supporting whichever Neo4j version I was using. 🙂 When Neo4j Aura added support for 4.0, I went ahead and updated that branch from Bolt v2 (introduced in Neo4j 3.4 and supported through 3.5.x) to v4 (Neo4j 4.0).

I was fine upgrading my own DB to 4.0 (again, I didn't realize anyone but me was using this shard), but I don't want to force you to upgrade yours to use a more ergonomic version of the driver. In hindsight, maybe I should've just gone to Bolt v3 so that both versions supported on Aura can use this driver. I didn't add support for all of the new features in Neo4j 4.0 (flow control, multiple DBs, etc), just updated the wire protocol, so it should be an easy change.

**Comment by petr-fischer** [comment]
@jgaskins Thanks for the info! Users of old Neo4j DB versions (3.x) can stick with older tagged releases of this shards, that is no problem for us (anyone).

**Comment by daliborfilus** [comment]
Hello! Can you please release the bolt v4 branch? Perhaps just as a new branch "bolt4" or something like that?
We've upgraded to Neo4j 4.x and I'm currently using your branch experimental-bolt-conversion just for that v4 support.
Btw ruby gem mysql2 has similar problems you have - I mean that they are dependent on the libmysqlclient driver versions and their solution is to maintain multiple different major versions of the gem, e.g. version 2.x supports mysql 5.x, version 3.x supports mysql 6.x, etc.
I know it's a lot of work to maintain two versions (one for 3.x and one for 4.x), it's just a suggestion.
But for now it would be great to have some branch for bolt 4 - I don't know how much experimental the experimental branch really is :-) or if those are features that will be in your new version.

**Comment by jgaskins** [comment]
@daliborfilus Sure. Honestly the number of times I've pointed an app at my branch and thought "I should merge this branch" is wild considering I _still haven't merged the branch_.

I'll go ahead and merge/release now while I'm thinking about it — crossing my fingers that I don't get distracted by something along the way. :joy:

**Comment by jgaskins** [comment]
@daliborfilus Alrighty, released `v0.7.0` with https://github.com/jgaskins/neo4j.cr/commit/04531bab211a1f0ff823c1cafcc2c320b1f43a9c.

Gonna go ahead and close this out since the issue mentioned in the title is fixed.
